// Workouts
export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const DELETE_SESSIONS = 'DELETE_SESSIONS';
export const RECIVED_WORKOUTS = 'RECIVED_WORKOUTS';
export const ADD_SESSION_TO_WORKOUT = 'ADD_SESSION_TO_WORKOUT';
export const REMOVE_SESSION_FROM_WORKOUT = 'REMOVE_SESSION_FROM_WORKOUT';
export const SET_WORKOUT_DATE = 'SET_WORKOUT_DATE';
export const WORKOUT_CREATED = 'WORKOUT_CREATED';
export const UPDATE_SESSION_IN_WORKOUT = 'UPDATE_SESSION_IN_WORKOUT';
export const REQUEST_WORKOUTS = 'REQUEST_WORKOUTS';
export const REQUEST_WORKOUTS_ABANDON = 'REQUEST_WORKOUTS_ABANDON';

// User
export const SET_USER = 'SET_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Exercises
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const NEW_EXERCISE = 'NEW_EXERCISE';
export const SET_EXERCISES_FROM_USER = 'SET_EXERCISES_FROM_USER';

// sessions
export const ADD_SESSIONS = 'ADD_SESSIONS';

// Sync
export const OFFLINE_SYNC_REMOVE = 'OFFLINE_SYNC_REMOVE';
